CREATE TABLE dbo.ETL_AUDIT_LOG (
    AUDIT_ID       BIGINT IDENTITY(1,1) PRIMARY KEY,
    WORKFLOW_NAME  NVARCHAR(200) NOT NULL,
    SESSION_NAME   NVARCHAR(200) NOT NULL,
    START_TIME     DATETIME2(0)  NOT NULL,
    END_TIME       DATETIME2(0)  NULL,
    ROWS_PROCESSED BIGINT        NULL,
    STATUS         NVARCHAR(20)  NOT NULL,
    HOSTNAME       NVARCHAR(128) NULL,
    RUN_GUID       UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE INDEX IX_ETL_AUDIT_LOG_Run
ON dbo.ETL_AUDIT_LOG (WORKFLOW_NAME, SESSION_NAME, START_TIME DESC);

ALTER TABLE dbo.ETL_AUDIT_LOG
DROP COLUMN ROWS_PROCESSED;

select * from ETL_AUDIT_LOG
